apiVersion: v1
kind: Secret
metadata:
  name: battlebot-backend-catalog-secret
  namespace: battlebot-backend
type: Opaque
stringData:
  DB_USER: ${DB_USER}
  DB_PASSWORD: ${DB_PASSWORD}
---
apiVersion: v1
kind: Secret
metadata:
  name: battlebot-backend-payment-secret
  namespace: battlebot-backend
type: Opaque
stringData:
  APPINSIGHTS_CONNECTION_STRING: ${APPINSIGHTS_CONNECTION_STRING}